openapi: 3.0.4
info:
  title: Case Management API
  version: 1.0.0
  description: |
    API สำหรับจัดการเคส เช่น ปิด alert, อัปเดตผล case_result, ปลดล็อกบัญชี และดูประวัติ
servers:
  - url: http://localhost:4000
    description: Internal network server

# ---------------------------------------------------------------
# ✨ Global security: ต้องมี Header `user_email`
# ---------------------------------------------------------------
security:
  - UserEmailHeader: []

tags:
  - name: User Accounts
    description: จัดการบัญชีผู้ใช้
  - name: Incidents
    description: จัดการ incidents (ปิด alert, อัปเดตผล)
  - name: History
    description: ดูประวัติการเปลี่ยนแปลง

components:
  # --------------------------------------
  # 🔐 Security scheme
  # --------------------------------------
  securitySchemes:
    UserEmailHeader:
      type: apiKey
      in: header
      name: user_email

  # --------------------------------------
  # 📦 Re-usable schemas
  # --------------------------------------
  schema:
    -http
    
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: ข้อความแสดงข้อผิดพลาด
    
    UserUnlockResult:
              type: object
              properties:
                user_email:
                  type: string
                  description: อีเมลผู้ใช้ที่ปลดล็อก
                account_status:
                  type: string
                  description: สถานะบัญชี เช่น "Unlocked"
                note:
                  $ref: '#/components/schemas/Note'
                error:
                  type: string
                  description: ข้อความแสดงข้อผิดพลาด (ถ้ามี)
              # ตัวอย่างจะเป็นแบบนี้:
              example:
                user_email: "user1@example.com"
                account_status: "Unlocked"
                note:
                  id: "note-123"
                  action: "Unlocked"
                  content: "Account unlocked"

    Note:
      type: object
      properties:
        id:
          type: string
        action:
          type: string
        content:
          type: string


    Incident:
      type: object
      properties:
        alert_id:
          type: string
        alert_name:
          type: string
        alert_status:
          type: string
        case_result:
          type: string
        notes:
          type: array
          items:
            $ref: '#/components/schemas/Note'

    HistoryEntry:
      type: object
      properties:
        authentication:
          type: object
          properties:
            user_email: { type: string }
            name:       { type: string }
            # id:         { type: string }
        user_agent: { type: string }
        ip_address: { type: string }
        action:     { type: string }
        case:
          oneOf:
            - $ref: '#/components/schemas/Incident'
            - $ref: '#/components/schemas/Note'

  responses:
    BadRequest:
      description: Request body หรือ parameter ไม่ถูกต้อง
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "Missing 'alert_id'"

    NotFound:
      description: Resource ไม่พบ
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "No incident found for alert_id XYZ"

    Conflict:
      description: พบข้อมูลซ้ำ
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "Multiple incidents found for alert_id ABC"

    InternalError:
      description: เกิดข้อผิดพลาดภายในเซิร์ฟเวอร์
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "Internal server error"

paths:
# =================================================================
# 🔓  PUT /accounts/unlock  – (ไม่เปลี่ยน logic)
# =================================================================
  /accounts/unlock:
    put:
      tags:
        - User Accounts
      summary: ปลดล็อกผู้ใช้ (single หรือ multi)
      security:
        - UserEmailHeader: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  required: [user_email]
                  properties:
                    user_email:
                      type: string
                - type: object
                  required: [users]
                  properties:
                    users:
                      type: array
                      items:
                        type: object
                        required: [user_email]
                        properties:
                          user_email:
                            type: string
            examples:
              SingleUser:
                summary: ปลดล็อกผู้ใช้คนเดียว
                value:
                  user_email: "user1@example.com"
              MultipleUsers:
                summary: ปลดล็อกผู้ใช้หลายคน
                value:
                  users:
                    - user_email: "user1@example.com"
                    - user_email: "user2@example.com"
      responses:
        '200':
          description: รายงานผลการปลดล็อก (อาจมี error รายการใดรายการหนึ่ง)
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserUnlockResult'
              example:
                results:
                  - user_email: "user1@example.com"
                    account_status: "Unlocked"
                    note:
                      id: "note-001"
                      action: "Unlocked"
                      content: "Account unlocked by admin"
                  - user_email: "missing@example.com"
                    error: "User not found"
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

# =================================================================
# 🛑  PUT /closedAlertStatus
# =================================================================
  /closedAlertStatus:
    put:
      tags: [Incidents]
      summary: ปิด `alert_status` เป็น Closed พร้อมเพิ่ม note
      security: [{ UserEmailHeader: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  required: [alert_id, alert_status]
                  properties:
                    alert_id:     { type: string }
                    alert_status: { type: string, enum: [Closed] }
                - type: object
                  required: [incidents]
                  properties:
                    incidents:
                      type: array
                      items:
                        type: object
                        required: [alert_id, alert_status]
                        properties:
                          alert_id:     { type: string }
                          alert_status: { type: string, enum: [Closed] }
            examples:
              SingleAlert:
                summary: ปิด alert เดียว
                value:
                  alert_id: "alert123"
                  alert_status: "Closed"
              MultipleAlerts:
                summary: ปิดหลาย alert
                value:
                  incidents:
                    - alert_id: "alert123"
                      alert_status: "Closed"
                    - alert_id: "alert456"
                      alert_status: "Closed"
      responses:
        '200':
          description: ปิดทั้งหมดสำเร็จ
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Incident'
        '207':
          description: สำเร็จบางรายการ
          $ref: '#/components/responses/InternalError'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

# =================================================================
# ✏️  PUT /updateCaseResult
# =================================================================
  /updateCaseResult:
    put:
      tags: [Incidents]
      summary: อัปเดต `case_result` พร้อมเพิ่ม note
      security: [{ UserEmailHeader: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  required: [alert_id, case_result, reason]
                  properties:
                    alert_id:
                      type: string
                    case_result:
                      type: string
                      enum: [WaitingAnalysis, TruePositives, FalsePositives, Analyzing]
                    reason:
                      type: string
                - type: object
                  required: [incidents]
                  properties:
                    incidents:
                      type: array
                      items:
                        type: object
                        required: [alert_id, case_result, reason]
                        properties:
                          alert_id:
                            type: string
                          case_result:
                            type: string
                            enum: [WaitingAnalysis, TruePositives, FalsePositives, Analyzing]
                          reason:
                            type: string
            examples:
              SingleCase:
                summary: update case ผลเคสเดี่ยว
                value:
                  alert_id: "alert123"
                  case_result: "TruePositives"
                  reason: "Confirmed as threat"
              MultipleCases:
                summary: update หลายเคส
                value:
                  incidents:
                    - alert_id: "alert123"
                      case_result: "TruePositives"
                      reason: "Confirmed"
                    - alert_id: "alert456"
                      case_result: "WaitingAnalysis"
                      reason: "Needs more review"
      responses:
        '200':
          description: อัปเดตสำเร็จทั้งหมด
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Incident'
        '207':
          description: สำเร็จบางส่วน
          $ref: '#/components/responses/InternalError'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

# =================================================================
# 📜  GET /history
# =================================================================
  /history:
    get:
      tags: [History]
      summary: ดึงหมดทุกประวัติการเปลี่ยนแปลง
      security: [{ UserEmailHeader: [] }]
      responses:
        '200':
          description: รายการ history
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HistoryEntry'
        '500':
          $ref: '#/components/responses/InternalError'
