openapi: 3.0.4
info:
  title: Case Management API
  description: API สำหรับจัดการเคส เช่น เพิ่ม, อัปเดตสถานะ, ผลลัพธ์, ลบ และดูประวัติ
  version: 1.0.0

servers:
  - url: http://localhost:4000
    description: Local development server

paths:
  /accounts/users:
    get:
      summary: Get list of user accounts
      description: ดึงข้อมูลรายชื่อผู้ใช้งานจาก GraphQL server ผ่าน endpoint `/accounts/users`
      tags:
        - User Accounts
      responses:
        "200":
          description: รายชื่อผู้ใช้งานทั้งหมด
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "123"
                    name:
                      type: string
                      example: "Alice"
                    user_email:
                      type: string
                      format: email
                      example: "alice@example.com"
        "500":
          description: เกิดข้อผิดพลาดจากฝั่งเซิร์ฟเวอร์
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Failed to fetch users"

  /accounts/unlock:
    put:
      summary: Unlock user account
      description: ปลดล็อกบัญชีผู้ใช้โดยใช้ user ID
      tags:
        - User Accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: string
                  example: "c54e7a4f-1d03-4f89-a18e-2a5d6f7b9d2b"
      responses:
        "200":
          description: Account unlocked successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  user_email:
                    type: string
                  account_status:
                    type: string
                    example: Active
        "400":
          description: Missing user ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Missing user ID
        "404":
          description: User not found or unlock failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: User not found or unlock failed
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to unlock account

  /caselist:
    get:
      summary: ดูรายการเคสทั้งหมด
      responses:
        "200":
          description: รายการเคสทั้งหมดในระบบ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Case"

  /history:
    get:
      summary: ดูประวัติการเปลี่ยนแปลงเคสทั้งหมด
      responses:
        "200":
          description: รายการประวัติทั้งหมด
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/HistoryEntry"

  /updateCaseStatus:
    put:
      summary: อัปเดตสถานะของเคส
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCaseStatusInput"
      responses:
        "200":
          description: เคสที่ถูกอัปเดตสถานะ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Case"
        "400":
          description: ข้อมูลไม่ถูกต้อง

  /updateCaseResult:
    put:
      summary: อัปเดตผลลัพธ์ของเคส
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCaseResultInput"
      responses:
        "200":
          description: เคสที่ถูกอัปเดตผลลัพธ์
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Case"
        "400":
          description: ข้อมูลไม่ถูกต้อง

  /deleteCase:
    delete:
      summary: ลบเคส
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteCaseInput"
      responses:
        "200":
          description: เคสที่ถูกลบ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Case"
        "400":
          description: ข้อมูลไม่ถูกต้อง
        "404":
          description: ไม่พบเคสที่ต้องการลบ

components:
  schemas:
    Case:
      type: object
      properties:
        token:
          type: string
          example: "testtoken"
        case_id:
          type: array
          items:
            type: string
          example: ["case123", "case456"]
        case_status:
          type: string
          enum: [Opened, Closed]
          nullable: true
          example: "Opened"
        case_result:
          type: string
          enum: [WaitingAnalysis, TruePositives, FalsePositives]
          nullable: true
          example: "TruePositives"
        timestamp:
          type: string
          format: date-time
          example: "2025-06-17T10:30:00Z"

    HistoryEntry:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          example: "2025-06-17T10:30:00Z"
        action:
          type: string
          example: "addCase"
        case:
          $ref: "#/components/schemas/Case"

    UpdateCaseStatusInput:
      type: object
      required:
        - token
        - case_id
        - case_status
      properties:
        token:
          type: string
          example: "testtoken"
        case_id:
          type: array
          items:
            type: string
          example: ["case123", "case456"]
        case_status:
          type: string
          enum: [Opened, Closed]
          example: "Opened"

    UpdateCaseResultInput:
      type: object
      required:
        - token
        - case_id
        - case_result
        - reason
      properties:
        token:
          type: string
          example: "testtoken"
        case_id:
          type: array
          items:
            type: string
          example: ["case123", "case456"]
        case_result:
          type: string
          enum: [WaitingAnalysis, TruePositives, FalsePositives]
          example: "TruePositives"
        reason:
          type: string
          example: "some reason"

    DeleteCaseInput:
      type: object
      required:
        - token
        - case_id
      properties:
        token:
          type: string
          example: "testtoken"
        case_id:
          type: array
          items:
            type: string
          example: ["case123", "case456"]
