# 📁 client/Dockerfile-client (production)
# 🧱 Build stage
FROM oven/bun:1.1.13 as build

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install

COPY . .

RUN bun run build

# 🌐 Serve stage
FROM nginx:stable-alpine

# ลบ default.conf ถ้าอยากใช้ config เอง (ไม่จำเป็นใน default case)
# RUN rm /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
