version: "3.8"
services:
  api:
    build:
      context: .
    container_name: My-Apollo-API
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    volumes:
      - ./server/data:/app/server/data
    restart: unless-stopped