version: "3.8"

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: my-apollo-api
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    volumes:
      - ./server/data:/app/data   # ถ้าใน container ใช้ /app/data หรือเปลี่ยนให้ถูก path
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile-client
    container_name: my-react-client
    ports:
      - "3000:80"  # แม็ป port 3000 บน host ไปยัง port 80 ใน container (nginx)
    env_file:
      - ./client/.env
    restart: unless-stopped

