version: "3.8"

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: my-apollo-api
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    volumes:
      - ./server/data:/app/data
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile-client
    container_name: my-react-client
    ports:
      - "3000:80"
    env_file:
      - ./client/.env
    restart: unless-stopped

